name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      registry_url: 'yemacr.azurecr.io'
      image_name: 'test/test-ubuntu'
      version: '1.0.0'
      latest_tag: true
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
