name: Test Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  call-reusable-workflow:
    uses: maidannikov/yem.workflow.dockerbuildpush/.github/workflows/dockerbuildpush.yml@master
    with:
      registry_url: 'yemacr.azurecr.io'
      image_name: 'test-image'
      latest_tag: true
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
